/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    useCookies?: boolean;
                    useSessionCookies?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccessTokenResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccessTokenResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/confirmEmail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MapIdentityApi-/api/auth/confirmEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/resendConfirmationEmail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResendConfirmationEmailRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgotPassword": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ForgotPasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/resetPassword": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResetPasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/manage/2fa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TwoFactorRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TwoFactorResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/manage/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InfoResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InfoRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InfoResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in account, or 204 when anonymous. */
        get: operations["GetAccount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out (clears the auth cookie). */
        post: operations["Logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account/handle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set the public handle used in /user/{handle}.
         * @description A handle is 3 to 32 characters: lower-case letters a-z, digits, '-' and '_'. Case-insensitive; stored in lower case. 409 when taken.
         */
        put: operations["SetHandle"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/brews/edit/{editId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The full brew for the editor (authors only), including the version to save against. */
        get: operations["GetBrewForEdit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/brews/share/{shareId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The read-only brew. Counts a view unless the caller is an author.
         * @description A locked brew answers 423 with the lock's share message as `detail` and its code as `code`.
         */
        get: operations["GetBrewForShare"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/brews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a brew (new or imported); the caller becomes its owner.
         * @description Optional `Idempotency-Key` header (1-128 visible ASCII characters, e.g. a UUID; surrounding quotes are stripped): within 24 hours, the same user sending the same key with the same request again gets 201 with the brew the first request created (as it is now) instead of a second brew; the same key with a different request is 422. A malformed key is 400 with errors['Idempotency-Key'].
         */
        post: operations["CreateBrew"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/brews/{editId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Save the whole brew against baseVersion (409 with the server version when stale).
         * @description Only doc, style, snippets and the metadata fields are written. An invited author becomes an author on their first save. Only the owner may change meta.authors.
         */
        put: operations["SaveBrew"];
        post?: never;
        /** Leave the brew as an author; the brew is deleted when no owner or author remains. */
        delete: operations["DeleteBrew"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/brews/{shareId}/clone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Copy a brew by share id into a new, unpublished brew owned by the caller. */
        post: operations["CloneBrew"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/brews/{editId}/lock/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask the moderators to review this brew's lock (authors only). Asking again keeps the first request time.
         * @description 409 when the brew is not locked. The admin review queue lists the brew until an admin unlocks it or dismisses the request.
         */
        post: operations["RequestLockReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vault": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search published brews (title, description and text), sorted and paged.
         * @description `q` uses web search syntax with the `simple` text search configuration (no stemming, any language). `sort`: relevance (default with `q`), updated (default without), created, views, title. `dir`: asc or desc (default asc for title, desc otherwise). `pageSize` is clamped to 1-60 (default 20) and `page` to 1-10000. An unknown `sort` or `dir`, or a `q` over 256 characters, is a 400 validation problem.
         */
        get: operations["SearchVault"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{handle}/brews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A user's brews: published ones for everyone; all of them, with edit ids, for the user. */
        get: operations["ListUserBrews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/themes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Static themes, published user themes, and the caller's own user themes. */
        get: operations["ListThemes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/themes/{theme}/bundle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A theme's inheritance chain, root first: stylesheets (URLs or raw user-theme CSS) and snippet sources.
         * @description `theme` is a static theme key (e.g. `5ePHB`) or a user theme's share id. 404 when it is neither; 422 (problem+json with `chain`) for a cycle, a chain longer than 8 themes, or a base theme that is missing or not tagged `meta:theme`; 423 when a theme brew in the chain is locked.
         */
        get: operations["GetThemeBundle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import/homebrewery/{shareId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The Homebrewery markdown of a brew on homebrewery.naturalcrit.com, by its share id.
         * @description Fetches `https://homebrewery.naturalcrit.com/download/{shareId}` and returns it as text/plain (the brew text with its ```metadata and ```css blocks). `shareId` must be 10-14 letters, digits, `_` or `-` (400 otherwise). 404 when the Homebrewery has no such brew, 413 when the text is over 2 MB, 502 when the Homebrewery fails, answers an error (then `upstreamStatus` holds its status; a locked brew answers its lock code), redirects or times out. Rate limited per user (429).
         */
        get: operations["ImportFromHomebrewery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Notifications to show now (startsAt <= now < stopsAt), oldest start first. */
        get: operations["ListActiveNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Site totals: brews, published brews, users, locked brews and pending lock reviews. */
        get: operations["AdminGetStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Accounts whose handle or email contains q (case-insensitive), or whose id is q; at most 50, exact matches first. */
        get: operations["AdminFindUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{handle}/brews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every brew of an account as the account itself sees them: unpublished, locked and invited ones included, with edit ids and roles. */
        get: operations["AdminListUserBrews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/brews/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A brew (without its document) by internal id, share id or edit id. */
        get: operations["AdminGetBrew"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/brews/{shareId}/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Lock a brew: its share page shows shareMessage (423) and its editor shows editMessage. Replaces an existing lock. */
        put: operations["AdminLockBrew"];
        post?: never;
        /** Remove a brew's lock (a no-op when it is not locked). */
        delete: operations["AdminUnlockBrew"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/brews/{shareId}/lock/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Dismiss the authors' review request and keep the lock (409 when the brew is not locked). */
        delete: operations["AdminDismissLockReview"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/locks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every locked brew, most recently locked first. */
        get: operations["AdminListLocks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/locks/review-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Locked brews whose authors asked for a review, oldest request first. */
        get: operations["AdminLockReviewQueue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every notification (past, current and future), newest start first. */
        get: operations["AdminListNotifications"];
        put?: never;
        /** Create a notification (409 when the dismiss key is taken). */
        post: operations["AdminCreateNotification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/notifications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One notification. */
        get: operations["AdminGetNotification"];
        /** Replace a notification's fields. */
        put: operations["AdminUpdateNotification"];
        post?: never;
        /** Delete a notification. */
        delete: operations["AdminDeleteNotification"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccessTokenResponse: {
            tokenType?: null | string;
            accessToken: string;
            /** Format: int64 */
            expiresIn: number;
            refreshToken: string;
        };
        /** @description The signed-in account (`GET /api/account/me`). */
        AccountInfo: {
            /** Format: uuid */
            id: string;
            handle: string;
            email: null | string;
            /** @description Role names, e.g. `["Admin"]`; empty for regular users. */
            roles: string[];
        };
        /** @description A brew for the admin pages (`GET /api/admin/brews/{id}`, lock changes). Never contains the document. */
        AdminBrewInfo: {
            /**
             * Format: uuid
             * @description The internal brew id.
             */
            id: string;
            shareId: string;
            editId: string;
            title: string;
            description: string;
            tags: string[];
            lang: string;
            theme: string;
            published: boolean;
            thumbnailUrl: null | string;
            /** Format: int32 */
            pageCount: number;
            /** Format: int32 */
            views: number;
            /** Format: int32 */
            version: number;
            /** Format: int32 */
            docSchemaVersion: number;
            /** @description All authors in display order, owner first (invited users included). */
            authors: components["schemas"]["BrewAuthorInfo"][];
            lock: null | components["schemas"]["AdminLockInfo"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            lastViewedAt: null | string;
        };
        /** @description A moderation lock as stored (both messages). */
        AdminLockInfo: {
            /**
             * Format: int32
             * @description Reason code (100-999), shown to authors and readers.
             */
            code: number;
            /** @description Shown to the authors in the editor. */
            editMessage: string;
            /** @description Shown instead of the brew on its share page. */
            shareMessage: string;
            /**
             * Format: date-time
             * @description When the lock was set.
             */
            applied: string;
            /**
             * Format: date-time
             * @description When an author asked for a review, or null.
             */
            reviewRequested: null | string;
        };
        /** @description Site totals (`GET /api/admin/stats`). */
        AdminStats: {
            /**
             * Format: int32
             * @description All brews.
             */
            brews: number;
            /**
             * Format: int32
             * @description Published brews (locked ones included).
             */
            publishedBrews: number;
            /**
             * Format: int32
             * @description Registered accounts.
             */
            users: number;
            /**
             * Format: int32
             * @description Brews with a moderation lock.
             */
            lockedBrews: number;
            /**
             * Format: int32
             * @description Locked brews whose authors asked for a review.
             */
            pendingReviews: number;
        };
        /** @description An account found by `GET /api/admin/users?q=`. */
        AdminUserInfo: {
            /** Format: uuid */
            id: string;
            handle: string;
            email: null | string;
            emailConfirmed: boolean;
            /** @description Role names, e.g. `["Admin"]`. */
            roles: string[];
            /**
             * Format: int32
             * @description Brews the user is an author of, in any role.
             */
            brewCount: number;
            /**
             * Format: date-time
             * @description Set while Identity's lockout (failed sign-ins) blocks the account.
             */
            lockoutEnd: null | string;
        };
        /** @enum {unknown} */
        AuthorRole: "owner" | "author" | "invited";
        /** @description An author of a brew. */
        BrewAuthorInfo: {
            /** @description Public handle (`/user/{handle}`). */
            handle: string;
            /** @description `owner`, `author`, or `invited` (can edit; becomes `author` on their first save). */
            role: components["schemas"]["AuthorRole"];
        };
        /** @description Everything the editor needs (`GET /api/brews/edit/{editId}`, and the result of create and clone). */
        BrewForEdit: {
            editId: string;
            shareId: string;
            /**
             * Format: int32
             * @description The version to send back as `baseVersion` on the next save.
             */
            version: number;
            /**
             * Format: int32
             * @description Schema version of Doc; the client migrates older documents on load.
             */
            docSchemaVersion: number;
            /** @description The document (plan §3.3): `{ "type": "doc", "content": [ page, … ] }`. */
            doc: components["schemas"]["RawJson"];
            /** @description User CSS. */
            style: string;
            /** @description User snippets (JSON array), or null. */
            snippets: components["schemas"]["RawJson"];
            /** @description The original Homebrewery markdown when the brew was imported, or null. */
            sourceMarkdown: null | string;
            meta: components["schemas"]["BrewMeta"];
            /** @description All authors in display order, owner first. */
            authors: components["schemas"]["BrewAuthorInfo"][];
            /** @description The caller's role. */
            role: components["schemas"]["AuthorRole"];
            /** Format: int32 */
            pageCount: number;
            /** Format: int32 */
            views: number;
            lock: null | components["schemas"]["BrewLockInfo"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description The read-only view (`GET /api/brews/share/{shareId}`). */
        BrewForShare: {
            shareId: string;
            /** @description Only for the brew's own authors (so the share page can link to the editor); otherwise null. */
            editId: null | string;
            /** Format: int32 */
            docSchemaVersion: number;
            doc: components["schemas"]["RawJson"];
            style: string;
            meta: components["schemas"]["BrewMeta"];
            /** @description Author handles in display order (invited users excluded). */
            authors: string[];
            /** Format: int32 */
            pageCount: number;
            /**
             * Format: int32
             * @description View count, including this view when it counted.
             */
            views: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description A moderation lock as the editor shows it. */
        BrewLockInfo: {
            /**
             * Format: int32
             * @description Lock reason code.
             */
            code: number;
            /** @description The lock's edit message for the authors. */
            message: string;
            /** Format: date-time */
            applied: string;
            /** Format: date-time */
            reviewRequested: null | string;
        };
        /** @description A brew's metadata, as stored. */
        BrewMeta: {
            /** @description At most 100 characters. When saved blank, the first heading of the document is used. */
            title: string;
            /** @description At most 500 characters. */
            description: string;
            /** @description Free-form tags (e.g. `type:adventure`, `meta:theme`); at most 50 of 100 characters. */
            tags: string[];
            /** @description Language code, e.g. `en`, `pt-BR`, `zh-Hant`. */
            lang: string;
            /**
             * @description A static theme key (`5ePHB`, `5eDMG`, `Blank`, `Journal`, `UnearthedArcana`)
             *         or the share id of a user theme.
             */
            theme: string;
            /** @description Listed in the vault and on the author's page. */
            published: boolean;
            /** @description Absolute http(s) URL used for link previews, or null. */
            thumbnailUrl: null | string;
        };
        /**
         * @description Metadata in a create or save request. Every field is optional: null (or missing) keeps the current value on
         *     save and uses the default on create. To clear a thumbnail send an empty string.
         */
        BrewMetaInput: {
            title?: null | string;
            description?: null | string;
            tags?: null | string[];
            lang?: null | string;
            theme?: null | string;
            published?: null | boolean;
            thumbnailUrl?: null | string;
            /**
             * @description The full author list as handles, in display order. Only the owner may change it on save
             *         (403 otherwise, unless the list is unchanged): new handles become `invited`, missing ones are removed, the
             *         owner always stays first. Unknown handles are a validation error. Null leaves the list unchanged.
             */
            authors?: null | string[];
        };
        /** @description A brew in a list (the vault, a user's page). Never contains the document. */
        BrewSummary: {
            shareId: string;
            /** @description Only in the caller's own list (`GET /api/users/{handle}/brews` as that user); otherwise null. */
            editId: null | string;
            title: string;
            description: string;
            tags: string[];
            /** @description Handles of the owner and authors in display order (invited users excluded). */
            authors: string[];
            /** @description A static theme key or a user theme's share id. */
            theme: string;
            lang: string;
            /** Format: int32 */
            pageCount: number;
            /** Format: int32 */
            views: number;
            /** @description Always true in the vault and in other people's lists. */
            published: boolean;
            thumbnailUrl: null | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /**
             * Format: date-time
             * @description When the share page last counted a view, or null.
             */
            lastViewedAt: null | string;
            role: null | components["schemas"]["AuthorRole"];
            /**
             * @description Whether a moderation lock blocks the share page. Locked brews appear only in their authors'
             *         own lists.
             */
            locked: boolean;
        };
        /** @description Body of `POST /api/brews` (a new brew, or an import). May be sent gzip-compressed. */
        CreateBrewRequest: {
            /** @description The document; omitted = one empty page. */
            doc?: unknown;
            /** @description User CSS. */
            style?: null | string;
            /** @description User snippets (JSON array), or null. */
            snippets?: unknown;
            meta?: null | components["schemas"]["BrewMetaInput"];
            /** @description For imports: the original Homebrewery markdown (kept for reference). */
            sourceMarkdown?: null | string;
            /**
             * Format: int32
             * @description The document's schema version; must be the server's current one when given.
             */
            docSchemaVersion?: null | number;
        };
        /** @description Result of `DELETE /api/brews/{editId}`. */
        DeleteBrewResponse: {
            /**
             * @description True when the caller was the last author and the brew is gone; false when only the
             *         caller was removed from the author list.
             */
            brewDeleted: boolean;
        };
        ForgotPasswordRequest: {
            email: string;
        };
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        InfoRequest: {
            newEmail?: null | string;
            newPassword?: null | string;
            oldPassword?: null | string;
        };
        InfoResponse: {
            email: string;
            isEmailConfirmed: boolean;
        };
        JsonElement: unknown;
        /** @description A locked brew in `GET /api/admin/locks` and the review queue. */
        LockedBrewInfo: {
            shareId: string;
            editId: string;
            title: string;
            /** @description Handles of the owner and authors in display order. */
            authors: string[];
            lock: components["schemas"]["AdminLockInfo"];
        };
        /** @description Body of `PUT /api/admin/brews/{shareId}/lock`. Replaces any existing lock (and clears its review request). */
        LockRequest: {
            /**
             * Format: int32
             * @description Reason code, 100-999 (upstream's lock tool defaults to 455).
             */
            code: null | number;
            /** @description Required; shown to the authors in the editor. At most 1000 characters. */
            editMessage: null | string;
            /** @description Required; shown instead of the brew on its share page. At most 1000 characters. */
            shareMessage: null | string;
        };
        LoginRequest: {
            email: string;
            password: string;
            twoFactorCode?: null | string;
            twoFactorRecoveryCode?: null | string;
        };
        /** @description A site notification (banner). */
        NotificationInfo: {
            /** Format: uuid */
            id: string;
            /** @description Unique key; the client remembers it when the user dismisses the notification. */
            dismissKey: string;
            title: string;
            /** @description Plain text (never markdown or HTML). */
            body: string;
            /**
             * Format: date-time
             * @description Shown from this time (inclusive).
             */
            startsAt: string;
            /**
             * Format: date-time
             * @description Shown until this time (exclusive).
             */
            stopsAt: string;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description Body of `POST /api/admin/notifications` and `PUT /api/admin/notifications/{id}`. */
        NotificationInput: {
            /** @description Required, unique, at most 100 characters (409 when another notification uses it). */
            dismissKey: null | string;
            /** @description Required, at most 200 characters. */
            title: null | string;
            /** @description Plain text, at most 10000 characters. */
            body: null | string;
            /**
             * Format: date-time
             * @description Default: now.
             */
            startsAt: null | string;
            /**
             * Format: date-time
             * @description Required; after StartsAt.
             */
            stopsAt: null | string;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
        };
        /**
         * @description JSON text written into a response as is: stored `jsonb` (a brew's doc and snippets) reaches the client
         *     without being parsed and re-serialized (plan §8.2). In the OpenAPI document it is an unconstrained value.
         */
        RawJson: unknown;
        RefreshRequest: {
            refreshToken: string;
        };
        RegisterRequest: {
            email: string;
            password: string;
        };
        ResendConfirmationEmailRequest: {
            email: string;
        };
        ResetPasswordRequest: {
            email: string;
            resetCode: string;
            newPassword: string;
        };
        /** @description Body of `PUT /api/brews/{editId}` (plan §8.4). May be sent gzip-compressed. */
        SaveBrewRequest: {
            /**
             * Format: int32
             * @description The version the client last loaded or saved. A different server version gives 409.
             */
            baseVersion: number;
            /** @description The whole document. */
            doc: components["schemas"]["JsonElement"];
            /** @description User CSS (null = empty). */
            style?: null | string;
            /** @description User snippets (JSON array); null clears them. */
            snippets?: unknown;
            meta?: null | components["schemas"]["BrewMetaInput"];
            /**
             * Format: int32
             * @description The document's schema version; must be the server's current one when given.
             */
            docSchemaVersion?: null | number;
        };
        /** @description A successful save. */
        SaveBrewResponse: {
            /**
             * Format: int32
             * @description The new version; send it as the next `baseVersion`.
             */
            version: number;
            /** Format: date-time */
            updatedAt: string;
            /** @description The stored title (the first heading when the title was blank). */
            title: string;
            /** Format: int32 */
            pageCount: number;
            /** @description The author list after the save. */
            authors: components["schemas"]["BrewAuthorInfo"][];
        };
        /** @description 409 body: the brew changed since `baseVersion` (another tab, device or author saved). */
        SaveConflict: {
            /**
             * Format: int32
             * @description The version now stored.
             */
            serverVersion: number;
        };
        /** @description Body of `PUT /api/account/handle`. */
        SetHandleRequest: {
            handle: null | string;
        };
        /**
         * @description Response of `GET /api/themes/{theme}/bundle` (plan §8.7): the theme's inheritance chain, root first. Apply
         *     `styles` in order, then the brew's own CSS.
         */
        ThemeBundle: {
            /** @description The theme that was asked for. */
            theme: string;
            /** @description Display name of that theme (a static theme's name or a user theme's title). */
            name: string;
            /** @description Owner handle of that theme when it is a user theme; otherwise null. */
            author: null | string;
            /**
             * @description Stylesheets, root first: the scoped URL of each static theme, then each user theme's CSS
             *         (raw: the client scopes it to the canvas, like user CSS). User themes without CSS add nothing.
             */
            styles: components["schemas"]["ThemeStyle"][];
            /**
             * @description Snippet sources, root first: a static theme's snippet group id (`V3_5ePHB`), or a user
             *         theme's snippets as `{ name, snippets }`. User themes without snippets add nothing.
             */
            snippets: components["schemas"]["ThemeSnippetRef"][];
        };
        /**
         * @description A static (built-in) theme: one entry of `/themes/themes.json`, which the web build writes
         *     (`web/vite/generateAssetsPlugin.ts`, `ThemeCatalogEntry`). `GET /api/themes` returns these entries
         *     as they are.
         */
        ThemeCatalogEntry: {
            /** @description Theme id, e.g. `5ePHB`; the value of a brew's `meta.theme`. Same as the folder name. */
            key: string;
            /** @description Display name, e.g. `5e PHB`. */
            name: string;
            /** @description Always `V3`. */
            renderer: string;
            /** @description Key of the theme whose CSS loads before this one, or null for a root theme. */
            baseTheme: null | string;
            /**
             * @description Key of the theme whose snippets upstream merged under this theme's, or null.
             *         Informational: upstream no longer uses it and the bundle ignores it.
             */
            baseSnippets: null | string;
            /** @description Folder name under `themes/V3` (legacy field). */
            path: string;
            /** @description URL of the compiled, unscoped stylesheet (export). */
            style: string;
            /** @description URL of the stylesheet scoped under `.hb-canvas` (editor canvas). */
            scopedStyle: string;
            /** @description URL of the theme picker preview image, or null. */
            preview: null | string;
            /** @description URL of the theme picker texture image, or null. */
            texture: null | string;
            /** @description Whether the theme has its own snippets (snippet group `V3_{key}`). */
            hasSnippets: boolean;
        };
        /** @description Response of `GET /api/themes`: every theme the caller can pick. */
        ThemeList: {
            /** @description The built-in themes, as in `/themes/themes.json`. */
            static: components["schemas"]["ThemeCatalogEntry"][];
            /**
             * @description User themes (brews tagged `meta:theme`): the caller's own first (published or not), then
             *         published ones, each group by name. At most 500.
             */
            user: components["schemas"]["UserThemeInfo"][];
        };
        /** @description A static theme's snippet group id (e.g. "V3_5ePHB"), or a user theme's name and snippets. */
        ThemeSnippetRef: string | {
            name: string;
            /** @description The user theme's snippets (JSON array). */
            snippets: unknown;
        };
        /** @description One stylesheet of a theme chain: `{ kind: 'url', href }` or `{ kind: 'css', css, shareId }`. */
        ThemeStyle: components["schemas"]["ThemeStyleThemeStyleUrl"] | components["schemas"]["ThemeStyleThemeStyleCss"];
        /** @description A user theme's CSS, unscoped. */
        ThemeStyleThemeStyleCss: {
            /** @enum {string} */
            kind: "css";
            /** @description The theme brew's CSS as stored. */
            css: string;
            /** @description The user theme it came from. */
            shareId: string;
        };
        /** @description A static theme's stylesheet (already scoped under `.hb-canvas`). */
        ThemeStyleThemeStyleUrl: {
            /** @enum {string} */
            kind: "url";
            /** @description Site-relative URL, e.g. `/themes/V3/Blank/style.scoped.css`. */
            href: string;
        };
        TwoFactorRequest: {
            enable?: null | boolean;
            twoFactorCode?: null | string;
            resetSharedKey?: boolean;
            resetRecoveryCodes?: boolean;
            forgetMachine?: boolean;
        };
        TwoFactorResponse: {
            sharedKey: string;
            /** Format: int32 */
            recoveryCodesLeft: number;
            recoveryCodes?: null | string[];
            isTwoFactorEnabled: boolean;
            isMachineRemembered: boolean;
        };
        /** @description A user's brews (`GET /api/users/{handle}/brews`), most recently updated first. */
        UserBrewList: {
            /** @description The user's handle. */
            handle: string;
            /**
             * @description True when the caller is this user: the list then includes unpublished and locked brews and brews
             *         the user is invited to, with edit ids and roles.
             */
            own: boolean;
            /** @description At most 1000 brews. In the user's own list, brews they are only invited to come after the others. */
            items: components["schemas"]["BrewSummary"][];
            /**
             * Format: int32
             * @description All brews the caller may see in this list (may exceed the items returned).
             */
            total: number;
        };
        /** @description A user theme: a brew tagged `meta:theme`, used as a theme by its share id. */
        UserThemeInfo: {
            /** @description The theme id to store in a brew's `meta.theme`. */
            shareId: string;
            /** @description The theme brew's title. */
            name: string;
            /** @description Handle of the theme brew's owner, or null. */
            author: null | string;
            /**
             * @description The theme this one builds on (the theme brew's own `meta.theme`): a static key or
             *         another user theme's share id.
             */
            baseTheme: string;
            /** @description The theme brew's thumbnail, or null. */
            thumbnailUrl: null | string;
            /** @description Whether the theme brew is published (listed for everyone). */
            published: boolean;
            /** @description Whether the caller is an owner or author of the theme brew. */
            mine: boolean;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description A page of vault results (`GET /api/vault`). */
        VaultPage: {
            items: components["schemas"]["BrewSummary"][];
            /**
             * Format: int32
             * @description Matching brews over all pages.
             */
            total: number;
            /**
             * Format: int32
             * @description The page returned (after clamping).
             */
            page: number;
            /**
             * Format: int32
             * @description The page size used (after clamping).
             */
            pageSize: number;
            /** @description The sort applied (`relevance` without `q` reports `updated`). */
            sort: string;
            /** @description The direction applied. */
            dir: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "MapIdentityApi-/api/auth/confirmEmail": {
        parameters: {
            query: {
                userId: string;
                code: string;
                changedEmail?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountInfo"];
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    SetHandle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetHandleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountInfo"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetBrewForEdit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                editId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrewForEdit"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetBrewForShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shareId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrewForShare"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Locked */
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CreateBrew: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBrewRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrewForEdit"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Payload Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    SaveBrew: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                editId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveBrewRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveBrewResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveConflict"];
                };
            };
            /** @description Payload Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    DeleteBrew: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                editId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteBrewResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CloneBrew: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shareId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrewForEdit"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Locked */
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    RequestLockReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                editId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrewLockInfo"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    SearchVault: {
        parameters: {
            query?: {
                q?: string;
                page?: number;
                pageSize?: number;
                sort?: "relevance" | "updated" | "created" | "views" | "title";
                dir?: "asc" | "desc";
                author?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VaultPage"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    ListUserBrews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserBrewList"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ListThemes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThemeList"];
                };
            };
        };
    };
    GetThemeBundle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                theme: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThemeBundle"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Locked */
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ImportFromHomebrewery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shareId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Payload Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ListActiveNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationInfo"][];
                };
            };
        };
    };
    AdminGetStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStats"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    AdminFindUsers: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserInfo"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    AdminListUserBrews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserBrewList"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    AdminGetBrew: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminBrewInfo"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    AdminLockBrew: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shareId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LockRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminBrewInfo"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    AdminUnlockBrew: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shareId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminBrewInfo"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    AdminDismissLockReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shareId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminBrewInfo"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    AdminListLocks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LockedBrewInfo"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    AdminLockReviewQueue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LockedBrewInfo"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    AdminListNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationInfo"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    AdminCreateNotification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationInfo"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    AdminGetNotification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationInfo"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    AdminUpdateNotification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationInfo"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    AdminDeleteNotification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
