// The bundled welcome brew (generated by scripts/welcome-doc.ts from upstream's welcome_msg.md).
import { getSchema } from '@tiptap/core';
import { describe, expect, it } from 'vitest';
import { DOC_SCHEMA_VERSION, schemaExtensions } from '@/editor/schema';
import { WELCOME, welcomeBrew } from './welcomeBrew';

describe('welcome brew', () => {
  it('is a valid document of the current schema', () => {
    expect(WELCOME.docSchemaVersion).toBe(DOC_SCHEMA_VERSION);
    expect(WELCOME.source).toBe('legacy/client/homebrew/pages/homePage/welcome_msg.md');
    const schema = getSchema(schemaExtensions);
    const node = schema.nodeFromJSON(WELCOME.doc);
    expect(() => node.check()).not.toThrow();
    // Upstream's two \page pages, both manual (pagination adds the rest at runtime).
    expect(node.childCount).toBe(2);
    node.forEach((page) => expect(page.attrs.kind).toBe('manual'));
    expect(node.textContent).toContain('The Homebrewery');
  });

  it('keeps the brew CSS, theme and language', () => {
    expect(WELCOME.theme).toBe('5ePHB');
    expect(WELCOME.lang).toBe('en');
    expect(WELCOME.style).toContain('.page');
  });

  it('becomes the home page brew: never saved, no ids', () => {
    const { content, brew } = welcomeBrew();
    expect(content).toBe(WELCOME.doc);
    expect(brew).toMatchObject({ editId: null, shareId: null, version: null, style: WELCOME.style, meta: { theme: '5ePHB', lang: 'en' } });
  });
});
